### ISSUE TITLE
Meshpy

### ISSUE THREAD

**Issue by stepjam** [BerkeleyAutomation/dex-net#1]
Hello,

Your version of **meshpy** seems to have disappeared (https://github.com/BerkeleyAutomation/meshpy.git)
I have tried to use the standard version, but it seems there are important changes you have made to it in your version.

Thanks.

**Comment by jeffmahler** [comment]
Thanks! Please try again. We just made the meshpy repository public. Sorry for the hiccup.

FYI our version of meshpy is completely independent from the standard version  and cannot be used. We are planning on replacing our version of meshpy with a fork of trimesh in the next version, which should be available in Fall 2017.

**Comment by stepjam** [comment]
Great. Thank you :)
