### ISSUE TITLE
Rescaling of vertices

### ISSUE THREAD

**Issue by taku-y** [BerkeleyAutomation/dex-net#14]
Hi,

When I'm trying to make a custom database for a project (`custom_databases` branch), I noticed a potential bug in object registration code for computing stable poses. In `MeshProcessor._clean_mesh()`, vertices are scaled with `MeshProcessor._rescale_vertices()` and those vertices are used for making convex hull. However, the center of mass in `Mesh3D.trimesh_`, which is used to compute stable poses, seems to calculate the center of mass with the vertices before the scaling. To explaing this, here's the data processing flow:

1. When loading mesh data in `MeshProcessor.generate_graspable()`, `Mesh3D.__init__()` is called.
2. In the init method, `Mesh3D.is_watertight` is called, then `Mesh3D.trimesh_` is set and the center of mass is computed.
3. In `MeshProcessor.generate_graspable()`, `MeshProcessor._clean_mesh()` is called.
4. In `MeshProcessor._clean_mesh()`, vertices are scaled with `MeshProcessor._rescale_vertices()`.

As a workaround, I added the following code in the end of `MeshProcessor._clean_mesh()`:

```
if rescale_mesh:
    self._rescale_vertices(scale, rescaling_type, use_uniform_com)
# Append following lines
self.mesh_.trimesh_ = None
self.mesh_.trimesh # initialize mesh_.trimesh_
if use_uniform_com: # adopted from somewhere in the code, I don'w know what this means
    self.mesh_.center_of_mass = self.mesh_._compute_com_uniform()
```

This code compute the center of mass again after the scaling.

I hope this report will help you.

**Comment by jeffmahler** [comment]
Thank you! PR's are welcome! I don't have time to fix all of these issues quickly unfortunately. Fixed in 1643b45
