### ISSUE TITLE
Missing triangle.py in meshpy

### ISSUE THREAD

**Issue by zy871125746** [BerkeleyAutomation/dex-net#16]
In order to visualize  stable poses for object in CLI, I have got a "No module named triangle" error. 

The meshpy is cloned from https://github.com/BerkeleyAutomation/meshpy.git and it dose not contain triangle.py in meshpy folder. How do I fix this error ? Thank you !
![image](https://user-images.githubusercontent.com/15799112/40159899-e9697e30-59dd-11e8-9a69-ac376bf1f572.png)

**Comment by jeffmahler** [comment]
I couldn't find any import for a module named triangle. Are you using the master branch of dex-net? Also, what version of trimesh do you have installed?

**Comment by zy871125746** [comment]
Thank for your answer, I am using master branch of dex-net and trimesh==2.30.11.  

By debugging, I found the error is caused by 460th line of visualizer3d.py in visualization modules (from https://github.com/BerkeleyAutomation/visualization.git).
![image](https://user-images.githubusercontent.com/15799112/40223815-ddf383a0-5ab6-11e8-9ad5-1cdf35a26778.png)

Trimesh calls meshpy.triangle moudle to create visualization,but in meshpy (from https://github.com/BerkeleyAutomation/meshpy.git) do not contain triangle moudle. I installed dex-net by run install.sh script, which install meshpy and visualizaiton automaticlly. Should I uninstall meshpy and install it with "pip install meshpy"?

**Comment by zy871125746** [comment]
Yes, I agree with you and I expect to see  next version. Thanks for your helping.

**Comment by as-wanfang** [comment]
@zy871125746 @jeffmahler , I found a way to work around it temporarily. After installing the meshpy package on PyPI, move the installed folder (/meshpy and /MeshPy-2018.1.dist-info) under your installation path (mine is /usr/local/lib/python2.7/dist-packages/meshpy) to your trimesh folder (/usr/local/lib/python2.7/dist-packages/trimesh). Next, move triangle.py under /mesh to ../ and change "import meshpy.triangle as triangle" to "import triangle as triangle". So that trimesh can found triangle module directly.

**Comment by simlei** [comment]
@as-wanfang @zy871125746 @jeffmahler an easier solution would be to just add the PyPI package ``triangle`` as a temporary dependency to dex-net, as the "real" meshpy is currently only imported once in the codebase of trimesh, and only if the PyPI package ``triangle`` is not found. 

It is not obvious from the error message, but a few lines of code above the ``meshpy`` import in the trimesh library, the ``triangle`` module is tried to be imported and the method returns before ``meshpy`` is touched on success.

For me, this solved the issue elegantly.

**Comment by jeffmahler** [comment]
@simlei Great find. This is the correct solution. Added to requirements.txt in 02a199a

**Comment by science-code** [comment]
Even though `requirements.txt` mentioned `triangle`, the error still persisted when running `python apps/dexnet_cli.py` and then steps 0-1-3:
```
INFO:dexnet.api:Displaying stable poses for
Stable pose pose_0 with p=0.116
Display object failed: cannot import name triangle
```


Solved simply with:
`python2 -m pip install --user triangle`
