### ISSUE TITLE
Can't run generate_gqcnn_dataset after adding new object

### ISSUE THREAD

**Issue by as-wanfang** [BerkeleyAutomation/dex-net#17]
Fail to run generate_gqcnn_dataset after adding new obj. The problem is that the stable poses for the new object have not been generated yet. Is there any function in the code deals wth this？ Thanks

**Comment by as-wanfang** [comment]
I guess I found it. It in the mesh_processor.py file under src/dexnet/database/.

**Comment by jeffmahler** [comment]
Sorry the instructions were not so good for this operation. That is correct, the stable poses need to be computed for each new object and the function to do so is in mesh processor. I highly recommend adding objects through the CLI as this will be done automatically

**Comment by wjydou** [comment]
@as-wanfang hey,how do you do with your own data to create the training set?

**Comment by ancorasir** [comment]
@wjydou In the end we didn't actually generate new training data. The pretrained model given by Jeff works quite nice at new objects. From our very limited experiments, the pretrained network can pick up all the items with suction cup. Very good job and thanks a lot for making it all open source @jeffmahler

**Comment by as-wanfang** [comment]
@wjydou  In the end we didn't actually generate new training data. The pretrained model given by Jeff works quite nice at new objects. From our very limited experiments, the pretrained network can pick up all the items with suction cup. Very good job and thanks a lot for making it all open source @jeffmahler
