### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by pyni** [BerkeleyAutomation/dex-net#28]
Hi, i have read the code about the ferrari_canny_L1().
And i have two questions:
1) It seems that this code does not do the judgement about  whether or not zero is in the convex hull.
 it use whether **min_norm_in_hull** is larger than a threshold. I think this may not be able to illustrate this point.

2) I can not understand,**min_norm_in_hull** has been calculated by the following code:
 **min_norm_in_hull, v = PointGraspMetrics3D.min_norm_vector_in_facet(G, wrench_regularizer=wrench_regularizer)**
While this distance is calculated again later by the following code:
        **for v in hull.vertices:
            if np.max(np.array(v)) < G.shape[1]: # because of some occasional odd behavior from pyhull
                facet = G[:, v] 
                dist, _ = PointGraspMetrics3D.min_norm_vector_in_facet(facet, wrench_regularizer=wrench_regularizer)
                if dist < min_dist:
                    min_dist = dist
                    closest_facet = v**
 I think both of them use the convex hull of G to calculate that distance.

**Comment by jeffmahler** [comment]
@pyni 

1. The idea is that you can solve a QP to determine the smallest magnitude of a vector in the convex hull of the grasp wrench space. If zero is in the convex hull, then the smallest magnitude is zero.

2. Note the difference in the first argument. In the first case, the matrix G is used to determine if the origin is inside the hull. In the second case, the closest point on each facet to the origin is computed.

**Comment by pyni** [comment]
Oh! I see. 
Thanks!!
