### ISSUE TITLE
Installation test failed'NameError: global name 'meshrender' is not defined'

### ISSUE THREAD

**Issue by wjydou** [BerkeleyAutomation/dex-net#32]
@jeffmahler
After installation, I executed the "python setup.py test",

running test
running egg_info
writing requirements to src/dex_net.egg-info/requires.txt
writing src/dex_net.egg-info/PKG-INFO
writing top-level names to src/dex_net.egg-info/top_level.txt
writing dependency_links to src/dex_net.egg-info/dependency_links.txt
reading manifest file 'src/dex_net.egg-info/SOURCES.txt'
writing manifest file 'src/dex_net.egg-info/SOURCES.txt'
running build_ext
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
WARNING:root:Failed to import ROS in Kinect2_sensor.py. Kinect will not be able to be used in bridged mode
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:Failed to import ROS in primesense_sensor.py. ROS functionality not available
WARNING:root:primesense_sensor.py not installed as catkin package. ROS functionality not available.
WARNING:root:Unable to import pyrealsense2.
WARNING:root:Failed to import ROS in realsense_sensor.py. ROS functionality not available
WARNING:root:realsense_sensor.py not installed as catkin package. ROS functionality not available.
WARNING:root:Failed to import ROS in ensenso_sensor.py. ROS functionality not available
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:root:Unable to import weight sensor modules!
Unable to import meshrender shared library! Rendering will not work. Likely due to missing Boost.Numpy
Boost.Numpy can be installed following the instructions in https://github.com/ndarray/Boost.NumPy
WARNING:trimesh:No FCL -- collision checking will not work
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import pyhull
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:dexnet.api:Failed to import DexNetVisualizer3D, visualization methods will be unavailable
test_illegal_create (test.database_test.Hdf5DatabaseTest) ... ok
test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest) ... Input mesh  /home/ncut1011/wjy_dex-net/catkin_ws_test/src/dex-net/data/test/models/bar_clamp.obj
output mesh  /home/ncut1011/wjy_dex-net/catkin_ws_test/src/dex-net/.dexnet/bar_clamp_proc.obj
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention obj
Mesh bar_clamp.obj loaded has 1428 vn 476 fn
No Script to apply.
Mesh /home/ncut1011/wjy_dex-net/catkin_ws_test/src/dex-net/data/test/models/bar_clamp.obj saved as /home/ncut1011/wjy_dex-net/catkin_ws_test/src/dex-net/.dexnet/bar_clamp_proc.obj (1428 vn 476 fn)
Reading data.
Warning: 9 lines were ignored since they did not contain faces or vertices.
Read in 1428 vertices and 476 faces.
Resolution: 0.000716689 with real dimension 0.064502
Center of grid 0 0 0
Bound box size: (-0.0358344 -0.0358344 -0.0358344) to (0.021729 0.02 0.032251) with dimensions 100 100 100.
Computing signed distance field.
Writing results to: .dexnet/bar_clamp_proc.sdf
Processing complete.
ERROR
test_gaussian_uniform_alloc (test.learning_test.LearningTest) ... ok
test_thompson_sampling (test.learning_test.LearningTest) ... ok
test_uniform_alloc (test.learning_test.LearningTest) ... ok
test_antipodal_grasp_sampler (test.grasping_test.GraspTest) ... ERROR:root:Singular matrix. Probably a bug
ok
test_contacts (test.grasping_test.GraspTest) ... ok
test_find_contacts (test.grasping_test.GraspTest) ... ok
test_force_closure (test.grasping_test.GraspTest) ... ok
test_grasp_quality_functions (test.grasping_test.GraspTest) ... ok
test_init_grasp (test.grasping_test.GraspTest) ... ok
test_init_graspable (test.grasping_test.GraspTest) ... ok
test_init_gripper (test.grasping_test.GraspTest) ... ok
test_min_norm_vector_in_facet (test.grasping_test.GraspTest) ... ok
test_wrench_in_positive_span (test.grasping_test.GraspTest) ... ok

======================================================================
ERROR: test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ncut1011/wjy_dex-net/catkin_ws_test/src/dex-net/test/database_test.py", line 168, in test_new_database_and_graspable
    stable_pose)
  File "/home/ncut1011/wjy_dex-net/catkin_ws_test/src/meshpy/meshpy/mesh_renderer.py", line 716, in wrapped_images_viewsphere
    return self.wrapped_images(mesh, vs_disc.object_to_camera_poses(), render_mode, stable_pose=stable_pose, mat_props=mat_props, light_props=light_props)
  File "/home/ncut1011/wjy_dex-net/catkin_ws_test/src/meshpy/meshpy/mesh_renderer.py", line 587, in wrapped_images
    debug=debug)
  File "/home/ncut1011/wjy_dex-net/catkin_ws_test/src/meshpy/meshpy/mesh_renderer.py", line 489, in images
    c, d = meshrender.render_mesh([P],
NameError: global name 'meshrender' is not defined

----------------------------------------------------------------------
Ran 15 tests in 110.712s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
Floating point exception

**Comment by sally-chen** [comment]
Hi @wjydou, I got the same error. Did you end up solving this? If so what did you do? Thanks in advance!

**Comment by wjydou** [comment]
@sally-chen I reinstall  the meshpy

**Comment by EvanLavizadeh** [comment]
Hi @wjydou,

This may sound like a silly question, but could you please provide steps on how exactly you reinstalled meshpy?

I tried: 
cd /dex-net/deps/meshpy
sudo sh install_meshrender.sh

No luck.

**Comment by wjydou** [comment]
@EvanLavizadeh
I have reappeared successfully. I don't know where you are wrong, and I want to see the results of your run.

**Comment by jzhang2008** [comment]
I got the same error. I also reinstall the meshpy but not solve it. I still set the path of meshrender.so in /etc/ld.so.conf. I  tried:
cd /dex-net/deps/meshpy/meshpy
>>python
import meshpy
sometimes I got the error:
Unable to import meshrender shared library! Rendering will not work. Likely due to missing Boost.Numpy
Boost.Numpy can be installed following the instructions in https://github.com/ndarray/Boost.NumPy
when I changed the path of meshrender.so in ~/.bashrc, this error disappears.
However, when I tried again
>>cd /dex-net
>>epython setup.py test
The same errors occur:
File "/home/jzhang/dex-net-master/deps/meshpy/meshpy/mesh_renderer.py", line 489, in images
c, d = meshrender.render_mesh([P],
NameError: global name 'meshrender' is not defined

If so what did you do? Thanks a lot

**Comment by zch-cpu** [comment]
> Hi @wjydou, I got the same error. Did you end up solving this? If so what did you do? Thanks in advance!

Have you solved it, bro? I've got the same issue. Thanks a lot!

**Comment by Ultraopxt** [comment]
I got the same error. Reinstall meshpy are useless for me :
test_init_grasp (test.grasping_test.GraspTest) ... ok
test_init_graspable (test.grasping_test.GraspTest) ... ok
test_init_gripper (test.grasping_test.GraspTest) ... ok
test_min_norm_vector_in_facet (test.grasping_test.GraspTest) ... ok
test_wrench_in_positive_span (test.grasping_test.GraspTest) ... ok

======================================================================
ERROR: test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adminis/qw/dex-net/test/database_test.py", line 168, in test_new_database_and_graspable
    stable_pose)
  File "/home/adminis/qw/dex-net/deps/meshpy/meshpy/mesh_renderer.py", line 716, in wrapped_images_viewsphere
    return self.wrapped_images(mesh, vs_disc.object_to_camera_poses(), render_mode, stable_pose=stable_pose, mat_props=mat_props, light_props=light_props)
  File "/home/adminis/qw/dex-net/deps/meshpy/meshpy/mesh_renderer.py", line 587, in wrapped_images
    debug=debug)
  File "/home/adminis/qw/dex-net/deps/meshpy/meshpy/mesh_renderer.py", line 489, in images
    c, d = meshrender.render_mesh([P],
NameError: global name 'meshrender' is not defined

----------------------------------------------------------------------
Ran 15 tests in 83.792s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>

**Comment by AhChaoispracting** [comment]
@qingweihk 
Hello, I have encountered the same problem as you, how did you solve it?
