### ISSUE TITLE
display object error at CLI

### ISSUE THREAD

**Issue by jiuweifox** [BerkeleyAutomation/dex-net#34]
Hello, I try to display the object in database example.hdf5, but there is nothing displayed in window and the error is like

Enter object key: nozzle
INFO:dexnet.api:Displaying nozzle
Display object failed: 'module' object has no attribute 'set_fps_limit'

Could you help me? Thanks very much!

**Comment by wjydou** [comment]
I have encountered this problem, but I have solved it. I uninstalled pyglet and reinstalled it.

**Comment by wjydou** [comment]
@jiuweifox I have encountered this problem, but I have solved it. I uninstalled pyglet and reinstalled it.

**Comment by jiuweifox** [comment]
@wjydou  Thanks you a lot! I fixed it follow what you said.

**Comment by wjydou** [comment]
@jiuweifox Are you in China? If you can, we can communicate via email.

**Comment by jiuweifox** [comment]
@wjydou   Actually I live in Japan.  But I am chinese, so I am very glad to communicate with you. My email is thu.lijian@gmail.com

**Comment by SimonePanicucci** [comment]
@wjydou I have the same problem but I can not fix it just reinstalling pyglet (installed version pyglet-1.4.2) can anyone please help me?
Many thanks.

**Comment by SimonePanicucci** [comment]
Solved using pyglet==1.3.2
