### ISSUE TITLE
Cannot find the smaller HDF5 Database

### ISSUE THREAD

**Issue by amritkochar** [BerkeleyAutomation/dex-net#41]
I am looking for the HDF5 database to run generate_gqcnn_dataset.py on but for some reason I cannot find it. 

Here I am not refering to the one which has a size of 13.8 GB ([link](https://berkeley.app.box.com/s/eaq37px77jxktr8ggti016pr3gpudp9l) but I am looking for the smaller dataset which has a size of 1.1 GB. 

Please share the link where I could download that from.

Thanks!

**Comment by amritkochar** [comment]
here is the link, 

https://berkeley.app.box.com/s/jnbwcj3zppcdhg5ffgf47ugqngosm40g/file/195608151692

**Comment by Aruen24** [comment]
> here is the link,
> 
> https://berkeley.app.box.com/s/jnbwcj3zppcdhg5ffgf47ugqngosm40g/file/195608151692

 It appears that the link has expired. Could you share an updated download link about the HDF5 Database
