### ISSUE TITLE
can't download the dataset and models

### ISSUE THREAD

**Issue by ghx0x0** [BerkeleyAutomation/dex-net#46]
Hi, I've installed the dex-net successfully in ROS mode. I run the scripts to download the datasets and models to try some examples:
        $ cd /path/to/your/gqcnn
        $ ./scripts/downloads/download_example_data.sh
        $ ./scripts/downloads/models/download_models.sh

but either of the dataset or models can be downloaded. the Info looks like below:

    #################     dataset      ##################
    ～$: wget -O GQCNN-2.0.zip https://berkeley.box.com/shared/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
    --2019-07-25 10:25:29--  https://berkeley.box.com/shared/static   /j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
    Resolving berkeley.box.com (berkeley.box.com)... 103.116.4.197
    Connecting to berkeley.box.com (berkeley.box.com)|103.116.4.197|:443... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: /public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip [following]
    --2019-07-25 10:25:29--  https://berkeley.box.com/public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
    Reusing existing connection to berkeley.box.com:443.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: https://berkeley.app.box.com/public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip [following]
    --2019-07-25 10:25:30--  https://berkeley.app.box.com/public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
    Resolving berkeley.app.box.com (berkeley.app.box.com)... 8.7.198.45
    Connecting to berkeley.app.box.com (berkeley.app.box.com)|8.7.198.45|:443... failed: Connection refused.

Can anyone help me ?  Thanks .

**Comment by ghx0x0** [comment]
> Hi, I've installed the dex-net successfully in ROS mode. I run the scripts to download the datasets and models to try some examples:
> $ cd /path/to/your/gqcnn
> $ ./scripts/downloads/download_example_data.sh
> $ ./scripts/downloads/models/download_models.sh
> 
> but either of the dataset or models can be downloaded. the Info looks like below:
> 
> ```
> #################     dataset      ##################
> Archive:  example_training_dataset_suction.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of example_training_dataset_suction.zip or
>         example_training_dataset_suction.zip.zip, and cannot find         example_training_dataset_suction.zip.ZIP, period.
> 
>  ################      models      ####################
>  Archive:  FC-GQCNN-4.0-PJ.zip
>    End-of-central-directory signature not found.  Either this file is not
>    a zipfile, or it constitutes one disk of a multi-part archive.  In the
>    latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
>  unzip:  cannot find zipfile directory in one of FC-GQCNN-4.0-PJ.zip or
>         FC-GQCNN-4.0-PJ.zip.zip, and cannot find FC-GQCNN-4.0-PJ.zip.ZIP, period.
>  Archive:  FC-GQCNN-4.0-SUCTION.zip
>    End-of-central-directory signature not found.  Either this file is not
>    a zipfile, or it constitutes one disk of a multi-part archive.  In the
>    latter case the central directory and zipfile comment will be found on
>    the last disk(s) of this archive.
>  unzip:  cannot find zipfile directory in one of FC-GQCNN-4.0-SUCTION.zip or
>          FC-GQCNN-4.0-SUCTION.zip.zip, and cannot find FC-GQCNN-4.0-SUCTION.zip.ZIP,   period.
> ```
> 
> Can anyone help me ? Thanks .

**Comment by visatish** [comment]
Here's what I get: 

```
wget -O GQCNN-2.0.zip https://berkeley.box.com/shared/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
--2019-07-24 19:42:55--  https://berkeley.box.com/shared/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
Resolving berkeley.box.com (berkeley.box.com)... 107.152.24.197
Connecting to berkeley.box.com (berkeley.box.com)|107.152.24.197|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip [following]
--2019-07-24 19:42:56--  https://berkeley.box.com/public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
Reusing existing connection to berkeley.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://berkeley.app.box.com/public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip [following]
--2019-07-24 19:42:56--  https://berkeley.app.box.com/public/static/j4k4z6077ytucxpo6wk1c5hwj47mmpux.zip
Resolving berkeley.app.box.com (berkeley.app.box.com)... 107.152.25.199
Connecting to berkeley.app.box.com (berkeley.app.box.com)|107.152.25.199|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!wUNeGX8pqgIchaVHgZOA6CWhX63oZM5fOHV1f0s3uXHDiNzF-2z_hNP4rJQNNrPywXpg39EQ6DKyfFYaz-ULkyZk9wg6Wr0LdTD72HBX7YD0p1FrZuM9kf4XyLaXwccYzw1Xu8GqhfP1qhj6fZ-fDZq5UdFg4P_6v25_3Iycu31PMpxb5g27V51Av3qq4wt84IyLvSxnJNc-KlfLYiitKlRqVs8MAhPlrzMA4IxBPMbsNPBg5XJ4rMBDFX-zTyPOm-9uXgvydmtXWQ8x3ziwBETlvjTLXV-_Y0WnF0feP_NAo-8lKYIJLpV8OTuViL310lrMzBRnzrM1RP70Mvk-PRw1tPbHbq6HPu-jQ8-eDNQ5lMQa74GzkYGEOOQi9hYEpZ2fOWd8gkMKwcVgBByW8crCnEKIDXfBgrBqE1KjOVXcaZni3UbFpBlNXgcvu8eG3mG21DhVv8WxrdL4pGyafrOIS_Qy4BvQkwksBnXYTLkPRHB4XQLbHY6Taq0sxwpLAWodN7y0_gi-rNarCAB06T4ZWmeNi_7RSgBZaLEOQO4OZjCedw2ATi-W-ENnSvaOuQALWCWfEEynx2bIaVppIP5Ipk_uywa89Q1ilqOXvB0mmNoFYrXgEXHYi-gUQnj3xWeiupsJtPh5n4r6ACYbah7Qzy8WomsRdYK_k84xI_iRRY6wpZ483Zg49IRZmFG9in2gYoXNgVADkmwRqf4uJgiw811gBGLwSCyBv9unsAWED3-ULR4WrV_qmaqu7t3L3FugI4XwSP-HMLFvb7s3pV5q199rOtPhHWWYdbTzHkpdqWheASdfJh1YWewGl7GbON7_pDPt4Ww8r8HSRiFwv8J4CNmmlXoP6IyCbgXMDNNgoawOs5t1FEGgH6pB2GFj-77f9t7DbjW3hm8NcdPmFqxF_IHiaVKCiE7gCMhyLsXk9_X4Av5ORVfPrMVCGKmVqJL6QcuXjrTuoAEZvjucb9wo_i-qAa-P_LVT6tGeQBsJAK9w_TAuSbBHJDPNVMVW56KLratcLjWnWLzS7YuQUqO1ViB-rtKZ8Pz81cLpTqm6AvZIqO7RXU65tAyl3CEAAw87tiKIpvEVh0ybB6WrerCbsbYo-eai1qEY6KTu6lt9Isif3nPp8F--5J-5VN9A_6ga22rgWzX5S0ypZOpETQBqS9yS1U6OQzWD_XxchzK2x-pJhq1boKwMWziDYYpH2noOtrhLNYZ2J47GUrW2oh0aHOwm5rHypJwqO75RqBEk-jjcHgKGtbOA4Vny-QhP5HEJXUhYBUCAavRJv8UytuqzASjde4p8PPnrBAG29DydSqRYG2Z6oaNZ_Cdwp0KLP3aNXTYW98lJmiPiQa8k4hjoh7coMub_5YlLH5JZedYym2Z_UN-LLylzYha4NntDPA../download [following]
--2019-07-24 19:42:57--  https://public.boxcloud.com/d/1/b1!wUNeGX8pqgIchaVHgZOA6CWhX63oZM5fOHV1f0s3uXHDiNzF-2z_hNP4rJQNNrPywXpg39EQ6DKyfFYaz-ULkyZk9wg6Wr0LdTD72HBX7YD0p1FrZuM9kf4XyLaXwccYzw1Xu8GqhfP1qhj6fZ-fDZq5UdFg4P_6v25_3Iycu31PMpxb5g27V51Av3qq4wt84IyLvSxnJNc-KlfLYiitKlRqVs8MAhPlrzMA4IxBPMbsNPBg5XJ4rMBDFX-zTyPOm-9uXgvydmtXWQ8x3ziwBETlvjTLXV-_Y0WnF0feP_NAo-8lKYIJLpV8OTuViL310lrMzBRnzrM1RP70Mvk-PRw1tPbHbq6HPu-jQ8-eDNQ5lMQa74GzkYGEOOQi9hYEpZ2fOWd8gkMKwcVgBByW8crCnEKIDXfBgrBqE1KjOVXcaZni3UbFpBlNXgcvu8eG3mG21DhVv8WxrdL4pGyafrOIS_Qy4BvQkwksBnXYTLkPRHB4XQLbHY6Taq0sxwpLAWodN7y0_gi-rNarCAB06T4ZWmeNi_7RSgBZaLEOQO4OZjCedw2ATi-W-ENnSvaOuQALWCWfEEynx2bIaVppIP5Ipk_uywa89Q1ilqOXvB0mmNoFYrXgEXHYi-gUQnj3xWeiupsJtPh5n4r6ACYbah7Qzy8WomsRdYK_k84xI_iRRY6wpZ483Zg49IRZmFG9in2gYoXNgVADkmwRqf4uJgiw811gBGLwSCyBv9unsAWED3-ULR4WrV_qmaqu7t3L3FugI4XwSP-HMLFvb7s3pV5q199rOtPhHWWYdbTzHkpdqWheASdfJh1YWewGl7GbON7_pDPt4Ww8r8HSRiFwv8J4CNmmlXoP6IyCbgXMDNNgoawOs5t1FEGgH6pB2GFj-77f9t7DbjW3hm8NcdPmFqxF_IHiaVKCiE7gCMhyLsXk9_X4Av5ORVfPrMVCGKmVqJL6QcuXjrTuoAEZvjucb9wo_i-qAa-P_LVT6tGeQBsJAK9w_TAuSbBHJDPNVMVW56KLratcLjWnWLzS7YuQUqO1ViB-rtKZ8Pz81cLpTqm6AvZIqO7RXU65tAyl3CEAAw87tiKIpvEVh0ybB6WrerCbsbYo-eai1qEY6KTu6lt9Isif3nPp8F--5J-5VN9A_6ga22rgWzX5S0ypZOpETQBqS9yS1U6OQzWD_XxchzK2x-pJhq1boKwMWziDYYpH2noOtrhLNYZ2J47GUrW2oh0aHOwm5rHypJwqO75RqBEk-jjcHgKGtbOA4Vny-QhP5HEJXUhYBUCAavRJv8UytuqzASjde4p8PPnrBAG29DydSqRYG2Z6oaNZ_Cdwp0KLP3aNXTYW98lJmiPiQa8k4hjoh7coMub_5YlLH5JZedYym2Z_UN-LLylzYha4NntDPA../download
Resolving public.boxcloud.com (public.boxcloud.com)... 107.152.24.200
Connecting to public.boxcloud.com (public.boxcloud.com)|107.152.24.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 102265339 (98M) [application/zip]
Saving to: ‘GQCNN-2.0.zip’

GQCNN-2.0.zip                    100%[========================================================>]  97.53M  20.4MB/s    in 5.5s    

2019-07-24 19:43:03 (17.7 MB/s) - ‘GQCNN-2.0.zip’ saved [102265339/102265339]
```

@jeffmahler do you know what could be going on here?

**Comment by jeffmahler** [comment]
@ghx0x0 Where are you trying to connect from? You may be having firewall issues. We cannot seem to replicate this.

**Comment by ghx0x0** [comment]
> @ghx0x0 Where are you trying to connect from? You may be having firewall issues. We cannot seem to replicate this.

thank you for your response. Seeing @visatish 's result, I think the reason is just the  firewall issues. I'm working in China.   

by the way, do your dataset and models has any copies on goole drives?  I can visit google in China. I'm interested in the awesome performance of your Dex net 4.0, I really want to replicate it .

**Comment by ghx0x0** [comment]
Thank you for your quick response, I located the  firewall issues :)

**Comment by ghx0x0** [comment]
I've solved the firewall problems, thank you everyone~

**Comment by LHJ1098826475** [comment]
您好，我看您成功下载了伯克利的dexnet的数据集，所以想请问一下为什么我都用VPN翻墙下载但总是下载到一半提示“dexnet_2_database.hdf5下载错误，未找到文件”，或者能麻烦你能将数据集分为几个小的压缩包分享给我吗？谢谢，谢谢！我已经加了您的QQ（我的QQ：1098826475），麻烦同意一下。或者可以加我微信15558155522，谢谢。
