### ISSUE TITLE
Meshlab conversion failed for .dexnet/bar_clamp_proc.obj

### ISSUE THREAD

**Issue by SnehalDikhale** [BerkeleyAutomation/dex-net#52]
snehal@snehal-G5-5587:~/catkin_erdal/src/dex-net$ python test/database_test.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
WARNING:root:Unable to import CNN modules! Likely due to missing tensorflow.
WARNING:root:TensorFlow can be installed following the instructions in https://www.tensorflow.org/get_started/os_setup
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:Unable to import pyrealsense2.
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
Unable to import meshrender shared library! Rendering will not work. Likely due to missing Boost.Numpy
Boost.Numpy can be installed following the instructions in https://github.com/ndarray/Boost.NumPy
WARNING:root:Failed to import gqcnn! Grasp2D functions will not be available.
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import pyhull
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:dexnet.api:Failed to import DexNetVisualizer3D, visualization methods will be unavailable
test_illegal_create (__main__.Hdf5DatabaseTest) ... ok
test_new_database_and_graspable (__main__.Hdf5DatabaseTest) ... sh: 1: meshlabserver: not found
INFO:root:MeshlabServer Command: meshlabserver -i "data/test/models/bar_clamp.obj" -o ".dexnet/bar_clamp_proc.obj"
ERROR

======================================================================
ERROR: test_new_database_and_graspable (__main__.Hdf5DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/database_test.py", line 91, in test_new_database_and_graspable
    mesh_processor.generate_graspable(CONFIG)
  File "/home/snehal/catkin_erdal/src/dex-net/test/dexnet/database/mesh_processor.py", line 157, in generate_graspable
    self._load_mesh(preproc_script)
  File "/home/snehal/catkin_erdal/src/dex-net/test/dexnet/database/mesh_processor.py", line 175, in _load_mesh
    raise ValueError('Meshlab conversion failed for %s' %(self.obj_filename))
ValueError: Meshlab conversion failed for .dexnet/bar_clamp_proc.obj

----------------------------------------------------------------------
Ran 2 tests in 0.028s

FAILED (errors=1)
INFO:rospy.core:signal_shutdown [atexit]
Floating point exception (core dumped)

**Comment by science-code** [comment]
The problem is the locale used by MeshLab.
See this solution: https://github.com/BerkeleyAutomation/dex-net/issues/49#issuecomment-552913419

**Comment by limbryan** [comment]
Hi, 

I am using the US locale but still get the same error. 

WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:Unable to import pyrealsense2.
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:tensorflow:From /home/mcube/Documents/git/dex-net/deps/gqcnn/gqcnn/utils/enums.py:44: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

root       WARNING  Failed to import gqcnn! Grasp2D functions will not be available.
root       WARNING  Failed to import OpenRAVE
root       WARNING  Failed to import OpenRAVE
test_illegal_create (__main__.Hdf5DatabaseTest) ... ok
test_new_database_and_graspable (__main__.Hdf5DatabaseTest) ... sh: 1: meshlabserver: not found
root       INFO     MeshlabServer Command: meshlabserver -i "data/test/models/bar_clamp.obj" -o ".dexnet/bar_clamp_proc.obj"
ERROR

======================================================================
ERROR: test_new_database_and_graspable (__main__.Hdf5DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/database_test.py", line 91, in test_new_database_and_graspable
    mesh_processor.generate_graspable(CONFIG)
  File "/home/mcube/Documents/git/dex-net/src/dexnet/database/mesh_processor.py", line 157, in generate_graspable
    self._load_mesh(preproc_script)
  File "/home/mcube/Documents/git/dex-net/src/dexnet/database/mesh_processor.py", line 175, in _load_mesh
    raise ValueError('Meshlab conversion failed for %s' %(self.obj_filename))
ValueError: Meshlab conversion failed for .dexnet/bar_clamp_proc.obj

----------------------------------------------------------------------
Ran 2 tests in 0.013s

**Comment by SnehalDikhale** [comment]
@science-code Thank you for the suggestion but that didn't work for me.

@limbryan: My problem was fixed by adding the Meshlab package. I hope that helps.
$sudo apt-get update -y
$sudo apt-get install -y meshlab
