### ISSUE TITLE
sklearn

### ISSUE THREAD

**Issue by Jasonleeo-cpu** [BerkeleyAutomation/dex-net#65]
Installed /home/lee/catkin_ws/src/meshpy
Processing dependencies for meshpy==0.1.0
Searching for sklearn
Reading https://pypi.python.org/simple/sklearn/
Couldn't find index page for 'sklearn' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for sklearn
error: Could not find suitable distribution for Requirement.parse('sklearn')

**Comment by Greg8978** [comment]
Have you try `pip install scikit-learn`?

**Comment by qingweihk** [comment]
> Installed /home/lee/catkin_ws/src/meshpy Processing dependencies for meshpy==0.1.0 Searching for sklearn Reading https://pypi.python.org/simple/sklearn/ Couldn't find index page for 'sklearn' (maybe misspelled?) Scanning index of all packages (this may take a while) Reading https://pypi.python.org/simple/ No local packages or download links found for sklearn error: Could not find suitable distribution for Requirement.parse('sklearn')

**Comment by qingweihk** [comment]
> Installed /home/lee/catkin_ws/src/meshpy Processing dependencies for meshpy==0.1.0 Searching for sklearn Reading https://pypi.python.org/simple/sklearn/ Couldn't find index page for 'sklearn' (maybe misspelled?) Scanning index of all packages (this may take a while) Reading https://pypi.python.org/simple/ No local packages or download links found for sklearn error: Could not find suitable distribution for Requirement.parse('sklearn')

Hi I meet the same question. How did you slove it?
Thanks very much!
