### ISSUE TITLE
A potential bug: close_fingers() in ParallelJawPtGrasp3D class

### ISSUE THREAD

**Issue by yongxf** [BerkeleyAutomation/dex-net#7]
Hi there, 
Thanks for providing this excellent code, it's very useful! 

I found a place that might be a bug: 
Currently,  the approach collision in close_fingers() function in ParallelJawPtGrasp3D class in dex-net/src/dexnet/grasping/grasp.py, the num_approach_samples is obtained by:

`num_approach_samples = int(Grasp.samples_per_grid * approach_dist / 2)`

but it seems the approach_dist should  be changed as grid in order to get the num_approach_samples:
```
approach_dist_grid = obj.sdf.transform_pt_obj_to_grid(approach_dist)
num_approach_samples = int(Grasp.samples_per_grid * approach_dist_grid / 2)
```
Thanks again for excellent code.

**Comment by jeffmahler** [comment]
@yongxf Thank you, that was a bug! This wouldn't have affected most users since the default API runs with approach checking off. I've fixed in master.
