### ISSUE TITLE
How is 6.7 million dataset generated from 1500 objects - the provided database generate around 1 million only

### ISSUE THREAD

**Issue by aprath1** [BerkeleyAutomation/dex-net#74]
Does any one know how 6.7 million dataset is generated using dexnet 2,0 database ?
dexnet 2.0 database - https://berkeley.app.box.com/s/eaq37px77jxktr8ggti016pr3gpudp9l
using the generate database code : https://github.com/BerkeleyAutomation/dex-net/blob/master/tools/generate_gqcnn_dataset.py
The resulting dataset is around 1 million only, so how is 6.7 million dataset generated?
Does it mean the same 'generate_gqcnn_dataset.py' script is run on the same dexnet 2.0 database multiple times?

**Comment by kondrauer** [comment]
You can alter images_per_stable_pose in cfg/tools/generate_gqcnn_dataset.yaml to get more datapoints. Its default is 5 if you choose a higher number you will get more.
