### ISSUE TITLE
Object Mesh Dataset v1.1 dataset is offline

### ISSUE THREAD

**Issue by Musambani** [BerkeleyAutomation/dex-net#78]
I would like to download the 3D-models from this link (provided in readme)
http://bit.ly/2uh07i9

unfortunately I do not have access or it is offline. Is there a way how I can download the files?
Thanks!

**Comment by vaew** [comment]
I also encountered the same problem, did you solve it?

**Comment by JaiminPatel1997** [comment]
Same problem with me, did anyone found some alternative link?

**Comment by JaiminPatel1997** [comment]
I think they haved moved their all data from box to Google drive.
You can find in below link:-
https://drive.google.com/file/d/1fbC0sGtVEUmAy7WPT_J-50IuIInMR9oO/view

**Comment by Musambani** [comment]
Awesome, thank you!
